"""initial schema

Revision ID: 16ee3524efa8
Revises: 
Create Date: 2026-04-15 20:36:26.063458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16ee3524efa8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_briefing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_briefing', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_briefing_date'), ['date'], unique=True)

    op.create_table('signal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.String(length=120), nullable=True),
    sa.Column('asset', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('timeframe', sa.String(length=20), nullable=True),
    sa.Column('signal_type', sa.String(length=20), nullable=False),
    sa.Column('market_trend', sa.String(length=20), nullable=True),
    sa.Column('risk_reward', sa.Float(), nullable=True),
    sa.Column('result_percent', sa.Float(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('news_sentiment', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signal_trade_id'), ['trade_id'], unique=True)

    op.create_table('telegram_dispatch_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('dedup_key', sa.String(length=255), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('content_ref', sa.String(length=255), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('telegram_dispatch_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_telegram_dispatch_logs_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_telegram_dispatch_logs_content_ref'), ['content_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_telegram_dispatch_logs_content_type'), ['content_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_telegram_dispatch_logs_dedup_key'), ['dedup_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_telegram_dispatch_logs_sent_at'), ['sent_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_telegram_dispatch_logs_tier'), ['tier'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_customer_id'),
    sa.UniqueConstraint('stripe_subscription_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_plan'), ['plan'], unique=False)

    op.create_table('trade_replays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('timeframe', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('replay_start', sa.DateTime(), nullable=False),
    sa.Column('replay_end', sa.DateTime(), nullable=False),
    sa.Column('entry_time', sa.DateTime(), nullable=False),
    sa.Column('exit_time', sa.DateTime(), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=True),
    sa.Column('result_percent', sa.Float(), nullable=True),
    sa.Column('market_context', sa.Text(), nullable=True),
    sa.Column('post_analysis', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trade_replays', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trade_replays_signal_id'), ['signal_id'], unique=False)

    op.create_table('replay_candles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_replay_id', sa.Integer(), nullable=False),
    sa.Column('candle_time', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('position_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trade_replay_id'], ['trade_replays.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('replay_candles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_replay_candles_candle_time'), ['candle_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_replay_candles_trade_replay_id'), ['trade_replay_id'], unique=False)

    op.create_table('replay_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_replay_id', sa.Integer(), nullable=False),
    sa.Column('event_time', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_level', sa.Float(), nullable=True),
    sa.Column('position_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trade_replay_id'], ['trade_replays.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('replay_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_replay_events_event_time'), ['event_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_replay_events_trade_replay_id'), ['trade_replay_id'], unique=False)

    op.create_table('user_replay_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trade_replay_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trade_replay_id'], ['trade_replays.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_replay_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_replay_decisions_trade_replay_id'), ['trade_replay_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_replay_decisions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_replay_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_replay_decisions_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_replay_decisions_trade_replay_id'))

    op.drop_table('user_replay_decisions')
    with op.batch_alter_table('replay_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_replay_events_trade_replay_id'))
        batch_op.drop_index(batch_op.f('ix_replay_events_event_time'))

    op.drop_table('replay_events')
    with op.batch_alter_table('replay_candles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_replay_candles_trade_replay_id'))
        batch_op.drop_index(batch_op.f('ix_replay_candles_candle_time'))

    op.drop_table('replay_candles')
    with op.batch_alter_table('trade_replays', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trade_replays_signal_id'))

    op.drop_table('trade_replays')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_plan'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('telegram_dispatch_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_telegram_dispatch_logs_tier'))
        batch_op.drop_index(batch_op.f('ix_telegram_dispatch_logs_sent_at'))
        batch_op.drop_index(batch_op.f('ix_telegram_dispatch_logs_dedup_key'))
        batch_op.drop_index(batch_op.f('ix_telegram_dispatch_logs_content_type'))
        batch_op.drop_index(batch_op.f('ix_telegram_dispatch_logs_content_ref'))
        batch_op.drop_index(batch_op.f('ix_telegram_dispatch_logs_content_hash'))

    op.drop_table('telegram_dispatch_logs')
    with op.batch_alter_table('signal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signal_trade_id'))

    op.drop_table('signal')
    with op.batch_alter_table('daily_briefing', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_briefing_date'))

    op.drop_table('daily_briefing')
    # ### end Alembic commands ###
