"""increase signal_type length

Revision ID: 4bc252c80800
Revises: ebc3de9f1fca
Create Date: 2026-04-23 11:20:19.511140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bc252c80800'
down_revision = 'ebc3de9f1fca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signal', schema=None) as batch_op:
        batch_op.alter_column('signal_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signal', schema=None) as batch_op:
        batch_op.alter_column('signal_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
