"""add telegram fields

Revision ID: 5c69178b18ce
Revises: 616c6fc79892
Create Date: 2026-04-19 11:04:08.113901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c69178b18ce'
down_revision = '616c6fc79892'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telegram_user_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('telegram_username', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('telegram_link_token', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('telegram_verified_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_telegram_link_token'), ['telegram_link_token'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_telegram_link_token'))
        batch_op.drop_column('telegram_verified_at')
        batch_op.drop_column('telegram_link_token')
        batch_op.drop_column('telegram_username')
        batch_op.drop_column('telegram_user_id')

    # ### end Alembic commands ###
