"""add challenge_score table

Revision ID: 5f379dad59b5
Revises: c876e4682af5
Create Date: 2026-07-02 15:15:43.674892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f379dad59b5'
down_revision = 'c876e4682af5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenge_score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pseudo', sa.String(length=40), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('rounds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('challenge_score', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_challenge_score_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_challenge_score_pseudo'), ['pseudo'], unique=False)
        batch_op.create_index(batch_op.f('ix_challenge_score_score'), ['score'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge_score', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_challenge_score_score'))
        batch_op.drop_index(batch_op.f('ix_challenge_score_pseudo'))
        batch_op.drop_index(batch_op.f('ix_challenge_score_created_at'))

    op.drop_table('challenge_score')
    # ### end Alembic commands ###
