"""add user replay decisions

Revision ID: 90f22f49fc2b
Revises: 
Create Date: 2026-04-09 09:47:58.404940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90f22f49fc2b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_replay_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trade_replay_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trade_replay_id'], ['trade_replays.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_replay_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_replay_decisions_trade_replay_id'), ['trade_replay_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_replay_decisions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_replay_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_replay_decisions_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_replay_decisions_trade_replay_id'))

    op.drop_table('user_replay_decisions')
    # ### end Alembic commands ###
