"""add token unlock events

Revision ID: c876e4682af5
Revises: da944a4b2e5b
Create Date: 2026-05-01 11:34:49.287749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c876e4682af5'
down_revision = 'da944a4b2e5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_unlock_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('unlock_date', sa.Date(), nullable=False),
    sa.Column('value_usd', sa.Float(), nullable=True),
    sa.Column('market_cap_usd', sa.Float(), nullable=True),
    sa.Column('market_cap_ratio', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(length=32), nullable=True),
    sa.Column('signal_level', sa.String(length=32), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'unlock_date', name='uq_token_unlock_symbol_date')
    )
    with op.batch_alter_table('token_unlock_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_token_unlock_events_risk_level'), ['risk_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_token_unlock_events_signal_level'), ['signal_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_token_unlock_events_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_token_unlock_events_unlock_date'), ['unlock_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_unlock_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_unlock_events_unlock_date'))
        batch_op.drop_index(batch_op.f('ix_token_unlock_events_symbol'))
        batch_op.drop_index(batch_op.f('ix_token_unlock_events_signal_level'))
        batch_op.drop_index(batch_op.f('ix_token_unlock_events_risk_level'))

    op.drop_table('token_unlock_events')
    # ### end Alembic commands ###
