"""add telegram dispatch log

Revision ID: d301ceb7cbfc
Revises: 90f22f49fc2b
Create Date: 2026-04-11 21:03:35.800319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd301ceb7cbfc'
down_revision = '90f22f49fc2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_dispatch_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('dedup_key', sa.String(length=255), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('content_ref', sa.String(length=255), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('telegram_dispatch_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_telegram_dispatch_logs_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_telegram_dispatch_logs_content_ref'), ['content_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_telegram_dispatch_logs_content_type'), ['content_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_telegram_dispatch_logs_dedup_key'), ['dedup_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_telegram_dispatch_logs_sent_at'), ['sent_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_telegram_dispatch_logs_tier'), ['tier'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telegram_dispatch_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_telegram_dispatch_logs_tier'))
        batch_op.drop_index(batch_op.f('ix_telegram_dispatch_logs_sent_at'))
        batch_op.drop_index(batch_op.f('ix_telegram_dispatch_logs_dedup_key'))
        batch_op.drop_index(batch_op.f('ix_telegram_dispatch_logs_content_type'))
        batch_op.drop_index(batch_op.f('ix_telegram_dispatch_logs_content_ref'))
        batch_op.drop_index(batch_op.f('ix_telegram_dispatch_logs_content_hash'))

    op.drop_table('telegram_dispatch_logs')
    # ### end Alembic commands ###
