"""add telegram invite table

Revision ID: ebc3de9f1fca
Revises: 5c69178b18ce
Create Date: 2026-04-19 23:09:50.292723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebc3de9f1fca'
down_revision = '5c69178b18ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_invite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('chat_id', sa.String(length=64), nullable=False),
    sa.Column('invite_link', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('telegram_user_id', sa.String(length=64), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_link')
    )
    with op.batch_alter_table('telegram_invite', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_telegram_invite_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_telegram_invite_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_telegram_invite_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_telegram_invite_is_revoked'), ['is_revoked'], unique=False)
        batch_op.create_index(batch_op.f('ix_telegram_invite_plan'), ['plan'], unique=False)
        batch_op.create_index(batch_op.f('ix_telegram_invite_telegram_user_id'), ['telegram_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_telegram_invite_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telegram_invite', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_telegram_invite_user_id'))
        batch_op.drop_index(batch_op.f('ix_telegram_invite_telegram_user_id'))
        batch_op.drop_index(batch_op.f('ix_telegram_invite_plan'))
        batch_op.drop_index(batch_op.f('ix_telegram_invite_is_revoked'))
        batch_op.drop_index(batch_op.f('ix_telegram_invite_expires_at'))
        batch_op.drop_index(batch_op.f('ix_telegram_invite_created_at'))
        batch_op.drop_index(batch_op.f('ix_telegram_invite_chat_id'))

    op.drop_table('telegram_invite')
    # ### end Alembic commands ###
